#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Nobara Linux' --class nobara {
    insmod btrfs
    search --no-floppy --fs-uuid --set=root 65198f8d-e1b0-4d50-94bc-15a1477279e7
    configfile /@/boot/grub2/grub.cfg
}