# ▄▄▄ .▐▄• ▄ ▄▄▄ . ▄▄· 
# ▀▄.▀· █▌█▌▪▀▄.▀·▐█ ▌▪
# ▐▀▀▪▄ ·██· ▐▀▀▪▄██ ▄▄
# ▐█▄▄▌▪▐█·█▌▐█▄▄▌▐███▌
#  ▀▀▀ •▀▀ ▀▀ ▀▀▀ ·▀▀▀ 

# Wallpaper
exec-once = awww-daemon --no-cache & sleep 1 && awww img $(find ~/Media/pictures/wallpapers/ -path "*/misc" -prune -o -type f -print | shuf -n 1) --transition-fps 60 --transition-type grow --transition-duration 0.8
# Polkit
exec-once = /usr/lib/polkit-1/polkit-agent-helper-1
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = waybar
exec-once = hyprctl setcursor GoogleDot-black 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme GoogleDot-black
exec-once = gammastep-indicator
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gnome-keyring-daemon --start --components=secrets

exec-once = hypridle
exec-once = swaync

# Optional features: Dock, Vicinae
# exec-once = nwg-dock-hyprland -p left -d -w 5 -nolauncher -ml 5 -l top -hl bottom
# exec-once = vicinae server

# Clipboard
exec-once = wl-paste --type text --watch cliphist -max-items=35 store
exec-once = wl-paste --type image --watch cliphist -max-items=10 store
exec-once = wl-clip-persist --clipboard regular

#exec-once = brightnessctl -s -d asus::kbd_backlight

# Run all startup scripts
exec-once = ~/.local/bin/auto_walls
exec-once = ~/.local/bin/at_startup
