foreground #e4e1e9
background #0d0e13
cursor #bcc2ff
cursor_text_color #0d0e13
selection_foreground #e4e1e9
selection_background #29292f
active_tab_foreground #e4e1e9
active_tab_background #181a2c
inactive_tab_foreground #91909a
inactive_tab_background #0d0e13
color0 #181a2c
color1 #ffb4ab
color2 #c4c5dd
color3 #93000a
color4 #bcc2ff
color5 #bcc2ff
color6 #e7b9d6
color7 #c7c5d0
color8 #91909a
color9 #ffb4ab
color10 #c4c5dd
color11 #93000a
color12 #bcc2ff
color13 #bcc2ff
color14 #e7b9d6
color15 #e4e1e9
