[window]
dynamic_title = false
padding.x = 10
padding.y = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "SemiBold Italic"

[cursor]
# style.shape = "Beam"
style.shape = "Underline"
style.blinking = "On"

[selection]
save_to_clipboard = true

[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/binds.toml"
]
