#!/bin/bash

WALLPAPER_LIGHT="$HOME/Nedia/pictures/wallpapers/dragons_lake_fog_white_boat_person.jpg"
WALLPAPER_DARK="$HOME/Media/pictures/wallpapers/rain_road_tree_foggy_bush_flowers_girl_umbrela_grey_outside_mountain.jpg"

if [[ $1 == "dark" ]]; then
    WALLPAPER=$WALLPAPER_DARK
else
    WALLPAPER=$WALLPAPER_LIGHT
fi

CURRENT_WALLPAPER=$(awww query -j | jq -r '.[""][].displaying.image')

if [[ $CURRENT_WALLPAPER != $WALLPAPER ]]; then
    ~/.local/bin/auto_walls set $WALLPAPER &
fi
