[window]
dynamic_title = false
padding.x = 10
padding.y = 10

[font.normal]
family = "SF Mono, Symbols Nerd Font"
style = "SemiBold"

[font.bold]
family = "SF Mono, Symbols Nerd Font"
style = "Bold"

[font.italic]
family = "SF Mono, Symbols Nerd Font"
style = "SemiBold Italic"

[cursor]
# style.shape = "Beam"
style.shape = "Underline"
style.blinking = "On"

[selection]
save_to_clipboard = true

[general]
import = ["colors.toml"]
