#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┏┏┓┳┓┓ ┏┓┳┓┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┣┫┗┫┃┃┣┫┃ ┣┫┃┃┃┃
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┗┛┣┛┛┗┗┛┛┗┛┗┻┛
#                       

$on_surface = rgba(e4e1e9ff)
$surface_alpha = rgba(131318cc)
$tertiary = rgba(e7b9d6ff)
$primary = rgba(bcc2ffff)
$surface = rgba(131318ff)
